// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace AgriEnergyPOE.Models;

public partial class Agri_Energy_DBContext : DbContext
{
    public Agri_Energy_DBContext()
    {
    }

    public Agri_Energy_DBContext(DbContextOptions<Agri_Energy_DBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Campaign> Campaign { get; set; }

    public virtual DbSet<ForumEntry> ForumEntry { get; set; }

    public virtual DbSet<Merchandise> Merchandise { get; set; }

    public virtual DbSet<User> Users { get; set; }

//    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
//#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
//        => optionsBuilder.UseSqlServer("Data Source=labVMH8OX\\SQLEXPRESS;Initial Catalog=Agri_Energy_DB;Integrated Security=True;Encrypt=True");

//    protected override void OnModelCreating(ModelBuilder modelBuilder)
//    {
//        modelBuilder.Entity<Campaign>(entity =>
//        {
//            entity.HasKey(e => e.CampaignId).HasName("PK__Campaign__3F5E8A99505174A0");
//        });

//        modelBuilder.Entity<ForumEntry>(entity =>
//        {
//            entity.HasKey(e => e.EntryId).HasName("PK__ForumEnt__F57BD2F772C52F37");
//        });

//        modelBuilder.Entity<Merchandise>(entity =>
//        {
//            entity.HasKey(e => e.MerchandiseId).HasName("PK__Merchand__F6F4C3F4049DE0E3");
//        });

//        modelBuilder.Entity<User>(entity =>
//        {
//            entity.HasKey(e => e.UserId).HasName("PK__Users__1788CC4C7AEDF746");
//        });

//        OnModelCreatingPartial(modelBuilder);
//    }

//    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}