// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace AgriEnergyPOE.Models;

[Table("Campaign")]
public partial class Campaign
{
    [Key]
    public int CampaignId { get; set; }

    [Required]
    [StringLength(50)]
    public string CampaignTitle { get; set; }

    [Required]
    [StringLength(700)]
    public string CampaignSummary { get; set; }

    [Required]
    [StringLength(15)]
    public string CoordinatorContact { get; set; }
}