// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace AgriEnergyPOE.Models;

[Table("ForumEntry")]
public partial class ForumEntry
{
    [Key]
    public int EntryId { get; set; }

    [Required]
    [StringLength(25)]
    public string EntrySubject { get; set; }

    [Required]
    [StringLength(200)]
    public string EntryContent { get; set; }

    public DateOnly PublishedDate { get; set; }
}