// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace AgriEnergyPOE.Models;

[Table("Merchandise")]
public partial class Merchandise
{
    [Key]
    public int MerchandiseId { get; set; }

    [Required]
    [StringLength(50)]
    public string MerchandiseName { get; set; }

    [Required]
    [StringLength(200)]
    public string MerchandiseDescription { get; set; }

    public DateOnly ManufactureDate { get; set; }

    [Required]
    [StringLength(20)]
    public string MerchandiseCost { get; set; }

    [Required]
    [StringLength(15)]
    public string ContactNumber { get; set; }
}